builds:
  - binary: kamanda
    goos:
      - windows
      - darwin
      - linux
      - freebsd
    goarch:
      - amd64
      - "386"
    # Custom ldflags templates.
    # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser`.
    ldflags:
      - -s -w -X github.com/mainawycliffe/kamanda/cmd.version={{.Version}} -X github.com/mainawycliffe/kamanda/cmd.commit={{.Commit}} -X github.com/mainawycliffe/kamanda/cmd.date={{.Date}} -X github.com/mainawycliffe/kamanda/cmd.builtBy=goreleaser
